title: "Pipou Pixel Works"
description: "Studio indépendant de développement de jeux mobile."
baseurl: ""
url: "https://pipoupixelworks.github.io"

theme: minima

collections:
  games:
    output: true
    permalink: /games/:name/

markdown: kramdown

exclude:
  - README.md

